name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: docs/.vitepress/dist

     # - name: Deploy to GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: docs/.vitepress/dist


      - name: Deploy for Github 
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: main
          folder: docs/.vitepress/dist
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true

